<template>
  <v-container id="receipt" class="d-flex flex-column">
    <v-row class="pt-2 mb-4 flex-shrink-1">
      <v-col class="bg-red pa-1" cols="1"></v-col>
      <v-col class="bg-green pa-1" cols="1"></v-col>
      <v-col class="bg-blue pa-1" cols="1"></v-col>
    </v-row>
    <v-row class="mt-3">
      <v-col class="d-flex flex-column">
        <v-spacer></v-spacer>
        <span class="text-h2 font-weight-medium">INVOICE</span>
      </v-col>
      <v-col>
        <v-img class="mb-3" height="100" :src="image" eager></v-img>
      </v-col>
    </v-row>
    <v-divider class="mt-3 mb-8"></v-divider>
    <v-row class="bg-grey lighten">
      <v-col class="d-flex flex-column" cols="5">
        <div class="text-grey text-button lh">INVOICE NUMBER</div>
        <div>#00001</div>
      </v-col>
      <v-col class="d-flex flex-column">
        <div class="text-grey text-button lh">DATE OF ISSUE</div>
        <div>{{ new Date().toLocaleDateString() }}</div>
      </v-col>
      <v-col></v-col>
    </v-row>
    <v-row :class="reservations.length > 5 ? 'mt-5' : 'mt-8'">
      <v-col class="pb-0" cols="7"></v-col>
      <v-col class="pb-0 text-h6">Hotel</v-col>
    </v-row>
    <v-row>
      <v-col class="d-flex flex-column text-body-2" cols="7">
        <div class="text-disabled">BILLED TO</div>
        <div>{{ user.full_name }}</div>
        <div>{{ user.email }}</div>
        <div>{{ user.phone }}</div>
      </v-col>
      <v-col class="d-flex flex-column text-body-2">
        <div>Aizu-Wakamatsu</div>
        <div>Fukushima Prefecture, Japan</div>
        <div>965-8580</div>
        <div>hotel@mail.co</div>
      </v-col>
    </v-row>
    <v-row :class="reservations.length > 5 ? 'mt-5' : 'mt-8'">
      <v-col class="pa-0">
        <v-container>
          <v-row id="table-header" class="mb-1 text-overline text-grey">
            <v-col class="pb-1" cols="7">Description</v-col>
            <v-col class="pb-1 text-end" cols="2">Check In</v-col>
            <v-col class="pb-1" cols="1">Days</v-col>
            <v-col class="pb-1 text-center" cols="2">Total</v-col>
          </v-row>
          <v-row
            v-for="(r, i) in reservations"
            class="table-row border-bottom my-1"
            :key="i"
          >
            <v-col cols="7">
              Room {{ r.room_name }} (Type {{ r.room_type }})
            </v-col>
            <v-col class="text-end" cols="2">
              {{ new Date(r.checkin).toLocaleDateString() }}
            </v-col>
            <v-col cols="1">
              {{
                (new Date(r.checkout).getTime() -
                  new Date(r.checkin).getTime()) /
                (1000 * 60 * 60 * 24)
              }}
            </v-col>
            <v-col class="text-center" cols="2">
              Rp.{{ Number(r.price).toLocaleString() }}
            </v-col>
          </v-row>
          <v-row class="table-row mt-3">
            <v-col class="py-1" cols="8"></v-col>
            <v-col class="py-1" cols="2">Subtotal:</v-col>
            <v-col class="py-1 pe-1 text-end" cols="2">
              Rp.{{ Number(total).toLocaleString() }}
            </v-col>
          </v-row>
          <v-row class="table-row">
            <v-col class="py-1" cols="8"></v-col>
            <v-col class="py-1" cols="2">Discount:</v-col>
            <v-col class="py-1 pe-1 text-end" cols="2">Rp.0</v-col>
          </v-row>
          <v-row class="table-row">
            <v-col class="py-1" cols="8"></v-col>
            <v-col class="py-1" cols="2">10% Tax:</v-col>
            <v-col class="py-1 pe-1 text-end" cols="2">
              Rp.{{ Number((total * 10) / 100).toLocaleString() }}
            </v-col>
          </v-row>
          <v-row class="table-row">
            <v-col class="py-1" cols="8"></v-col>
            <v-col class="py-1" cols="2">Total:</v-col>
            <v-col class="py-1 pe-1 text-end" cols="2">
              Rp.{{ Number(total - (total * 10) / 100).toLocaleString() }}
            </v-col>
          </v-row>
        </v-container>
      </v-col>
    </v-row>
    <v-spacer></v-spacer>
    <v-row class="font-italic text-caption">
      <v-col>This is an invoice generated by website</v-col>
      <v-col cols="auto">All rights reserved &copy; 2022 by sglkc</v-col>
    </v-row>
  </v-container>
</template>

<style scoped>
.bg-grey.lighten {
  background-color: #eceff1 !important;
}

.lh {
  line-height: 1.5;
}

.table-row {
  font-size: 0.9em;
}

.border-bottom {
  border-bottom: 1px black solid;
}

.v-row {
  flex: 0;
  margin: 0;
}

#receipt {
  max-width: 640px;
  min-height: 1000px;
  z-index: 1000;
}

.lines {
  max-height: 1rem;
}

#title {
  font-size: 52px;
  font-weight: lighter;
}

#table-header {
  border-bottom: 3px solid black;
}
</style>

<script>
import axios from "axios";
import image from "@/assets/receipt.png";

export default {
  name: "Receipt",
  data() {
    return {
      image,
      reservations: [],
    };
  },
  computed: {
    user() {
      return this.store.state.USER;
    },
    total() {
      return this.reservations.reduce((a, b) => (a = a + b.price), 0);
    },
  },
  created() {
    axios
      .get(
        import.meta.env.VITE_API +
          `/services/users/${this.user.id}/reservations`,
        {
          headers: {
            Authorization: "bearer " + this.store.state.JWT_TOKEN,
          },
        }
      )
      .then((res) => {
        this.reservations = res.data.result;
      })
      .catch((err) => {
        console.error(err.response?.data.error ?? err);
      });
  },
};
</script>
